// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOoIEEfESrOY97qOwAw4Hc4TIPcPfyBqc',
    appId: '1:450722208376:web:d202501f9a621b35bb6b8d',
    messagingSenderId: '450722208376',
    projectId: 'ownitoo-3d6b0',
    authDomain: 'ownitoo-3d6b0.firebaseapp.com',
    storageBucket: 'ownitoo-3d6b0.appspot.com',
    measurementId: 'G-GK22KEZ6KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2qlyIRtrnmtuvVVwgTlFIP8XnJZQvHzk',
    appId: '1:450722208376:android:d3c42cd7623cf8c4bb6b8d',
    messagingSenderId: '450722208376',
    projectId: 'ownitoo-3d6b0',
    storageBucket: 'ownitoo-3d6b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsza1a-T0vZjt0heNAUuQPrPZ548cw0JE',
    appId: '1:450722208376:ios:cb813fac67213644bb6b8d',
    messagingSenderId: '450722208376',
    projectId: 'ownitoo-3d6b0',
    storageBucket: 'ownitoo-3d6b0.appspot.com',
    androidClientId: '450722208376-s91fp69pdcbcrcnkgk7eorlv8hi2ueda.apps.googleusercontent.com',
    iosClientId: '450722208376-7ju010ac1h7s4n76co8bv8s8mh1aoni1.apps.googleusercontent.com',
    iosBundleId: 'com.app.ownitoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsza1a-T0vZjt0heNAUuQPrPZ548cw0JE',
    appId: '1:450722208376:ios:bdf6e8b08488de75bb6b8d',
    messagingSenderId: '450722208376',
    projectId: 'ownitoo-3d6b0',
    storageBucket: 'ownitoo-3d6b0.appspot.com',
    androidClientId: '450722208376-s91fp69pdcbcrcnkgk7eorlv8hi2ueda.apps.googleusercontent.com',
    iosClientId: '450722208376-78fqrrhj3acpfslij9shgua19dd8bgiv.apps.googleusercontent.com',
    iosBundleId: 'com.app.onito.RunnerTests',
  );
}
