class Routes {
  Routes._();
  static const String splashScreen = "/SplashScreen";
  static const String loginScreen = "/LoginScreen";
  static const String bottomScreen = "/BottomScreen";
  static const String homeScreen = "/HomeScreen";
  static const String settingScreen = "/SettingScreen";
  static const String onboardingScreen = "/OnBoardingScreen";
  static const String forgotScreen = "/ForgotScreen";
  static const String verificationScreen = "/VerificationScreen";
  static const String menScreen = "/MenScreen";
  static const String filterScreen = "/FilterScreen";
  static const String denimScreen = "/DenimScreen";
  static const String paymentScreen = "/PaymentScreen";
  static const String productScreen = "/ProductScreen";
  static const String signupScreen = "/SignupScreen";
  static const String categoryScreen = "/CategoryScreen";
  static const String homebidScreen = "/HomeBidScreen";
  static const String notificationScreen = "/NotificationScreen";
  static const String favouriteScreen = "/FavouriteScreen";
  static const String menshirtScreen = "/MenshirtScreen";
  static const String biddingScreen = "/BiddingScreen";
  static const String messageScreen = "/MessageScreen";
  static const String passwordScreen = "/PasswordScreen";
  static const String settingPaymentScreen = "/SettingPaymentScreen";
  static const String addressScreen = "/AddressScreen";
  static const String newAddressScreen = "/NewAddressScreen";
  static const String mySubscription = "/MySubscription";
  static const String cmsScreen = "/CmsScreen";
  static const String navBarMessage = "/NavBarMessage";
  static const String sellItem = "/SellItem";
  static const String gyaradoMsgScreen = "/GyaradoMsgScreen";
  static const String profileScreen = "/ProfileScreen";
  static const String editProfileScreen = "/EditProfileScreen";
}
